# Generated by Django 3.1.3 on 2020-11-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlte')),
                ('title_description', models.CharField(max_length=400, verbose_name='TittleDescription')),
                ('picture', models.ImageField(upload_to='')),
                ('item_name', models.CharField(max_length=50, verbose_name='ItemName')),
                ('item_description', models.CharField(max_length=50, verbose_name='ItemName')),
                ('item_link', models.CharField(max_length=400, verbose_name='Link')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top10.category')),
            ],
        ),
    ]
