# Generated by Django 3.1.3 on 2020-11-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='item_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='item_name',
        ),
        migrations.CreateModel(
            name='PostItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='ItemName')),
                ('item_description', models.CharField(max_length=50, verbose_name='ItemName')),
                ('item_link', models.CharField(max_length=400, verbose_name='Link')),
                ('description', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top10.post')),
            ],
        ),
    ]
