# Generated by Django 3.1.3 on 2020-11-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0002_auto_20201126_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_description',
            field=models.CharField(max_length=50, verbose_name='ItemDescription'),
        ),
    ]
