# Generated by Django 3.1.3 on 2020-11-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0003_auto_20201126_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.CreateModel(
            name='Pros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pros_title', models.CharField(max_length=200, verbose_name='Pros')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top10.postitem')),
            ],
        ),
    ]
