# Generated by Django 3.1.3 on 2020-11-30 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0005_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cons_title', models.CharField(max_length=200, verbose_name='Cons')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top10.postitem')),
            ],
        ),
    ]
