# Generated by Django 3.1.3 on 2020-11-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0006_cons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='picture_main',
        ),
    ]
