# Generated by Django 3.1.3 on 2020-12-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0008_auto_20201201_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='item_title',
            field=models.CharField(default='-', max_length=500, verbose_name='Item title'),
        ),
    ]
