# Generated by Django 3.1.3 on 2020-12-01 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0009_postitem_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='item_picture',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_title',
            field=models.CharField(max_length=500, verbose_name='Item title'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='top10.post')),
            ],
        ),
    ]
