# Generated by Django 3.1.3 on 2020-12-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0012_auto_20201201_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_name',
            new_name='user_name',
        ),
    ]
