# Generated by Django 3.1.4 on 2020-12-08 13:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0014_auto_20201208_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
