# Generated by Django 3.1.4 on 2020-12-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0015_auto_20201208_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_row', models.CharField(max_length=200, null=True, verbose_name='Table row')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='table_row',
            field=models.ManyToManyField(to='top10.Table'),
        ),
    ]
