# Generated by Django 3.1.4 on 2020-12-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0016_auto_20201208_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='table_row',
        ),
        migrations.AddField(
            model_name='table',
            name='post_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='top10.post'),
        ),
    ]
