# Generated by Django 3.1.4 on 2020-12-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0017_auto_20201208_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='item_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Post item name(What kind of items will be appear in this post)'),
        ),
    ]
