# Generated by Django 3.1.4 on 2020-12-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0019_postitem_table_row'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='TableRow',
        ),
        migrations.RemoveField(
            model_name='postitem',
            name='table_row',
        ),
    ]
