# Generated by Django 3.1.4 on 2020-12-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0020_auto_20201208_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_value', models.CharField(max_length=200, null=True, verbose_name='Table value')),
                ('post_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='top10.postitem')),
            ],
        ),
    ]
