# Generated by Django 3.1.4 on 2020-12-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0022_post_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImportance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('Must read', 'Must read'), ('Hot this week', 'Hot this week')], max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='importance',
            field=models.ManyToManyField(to='top10.PostImportance'),
        ),
    ]
